export const translatedCountryNames: Record<string, Record<string, string>> = {
    "Afghanistan": {
        "de": "Afghanistan",
        "en": "Afghanistan",
        "pl": "Afganistan",
        "es": "Afganistán",
        "fr": "Afghanistan",
        "it": "Afghanistan",
        "pt": "Afeganistão",
        "ru": "Афганистан",
        "tr": "Afganistan",
        "zh": "阿富汗",
        "ja": "アフガニスタン"
    },
    "Aland Islands": {
        "de": "Ålandinseln",
        "en": "Aland Islands",
        "pl": "Wyspy Alandzkie",
        "es": "Islas Åland",
        "fr": "Îles Åland",
        "it": "Isole Åland",
        "pt": "Ilhas de Aland",
        "ru": "Аландские острова",
        "tr": "Aland Adaları",
        "zh": "奥兰群岛",
        "ja": "オーランド諸島"
    },
    "Albania": {
        "de": "Albanien",
        "en": "Albania",
        "pl": "Albania",
        "es": "Albania",
        "fr": "Albanie",
        "it": "Albania",
        "pt": "Albânia",
        "ru": "Албания",
        "tr": "Arnavutluk",
        "zh": "阿尔巴尼亚",
        "ja": "アルバニア"
    },
    "Algeria": {
        "de": "Algerien",
        "en": "Algeria",
        "pl": "Algieria",
        "es": "Argelia",
        "fr": "Algérie",
        "it": "Algeria",
        "pt": "Argélia",
        "ru": "Алжир",
        "tr": "Cezayir",
        "zh": "阿尔及利亚",
        "ja": "アルジェリア"
    },
    "American Samoa": {
        "de": "Amerikanisch-Samoa",
        "en": "American Samoa",
        "pl": "Samoa Amerykańskie",
        "es": "Samoa Americana",
        "fr": "Samoa américaines",
        "it": "Samoa Americane",
        "pt": "Samoa Americana",
        "ru": "Американское Самоа",
        "tr": "Amerikan Samoası",
        "zh": "美属萨摩亚",
        "ja": "アメリカ領サモア"
    },
    "Andorra": {
        "de": "Andorra",
        "en": "Andorra",
        "pl": "Andora",
        "es": "Andorra",
        "fr": "Andorre",
        "it": "Andorra",
        "pt": "Andorra",
        "ru": "Андорра",
        "tr": "Andorra",
        "zh": "安道尔",
        "ja": "アンドラ"
    },
    "Angola": {
        "de": "Angola",
        "en": "Angola",
        "pl": "Angola",
        "es": "Angola",
        "fr": "Angola",
        "it": "Angola",
        "pt": "Angola",
        "ru": "Ангола",
        "tr": "Angola",
        "zh": "安哥拉",
        "ja": "アンゴラ"
    },
    "Anguilla": {
        "de": "Anguilla",
        "en": "Anguilla",
        "pl": "Anguilla",
        "es": "Anguila",
        "fr": "Anguilla",
        "it": "Anguilla",
        "pt": "Anguilla",
        "ru": "Ангилья",
        "tr": "Anguilla",
        "zh": "安圭拉",
        "ja": "アンギラ"
    },
    "Antarctica": {
        "de": "Antarktis",
        "en": "Antarctica",
        "pl": "Antarktyda",
        "es": "Antártida",
        "fr": "Antarctique",
        "it": "Antartide",
        "pt": "Antártida",
        "ru": "Антарктида",
        "tr": "Antarktika",
        "zh": "南极洲",
        "ja": "南極大陸"
    },
    "Antigua and Barbuda": {
        "de": "Antigua und Barbuda",
        "en": "Antigua and Barbuda",
        "pl": "Antigua i Barbuda",
        "es": "Antigua y Barbuda",
        "fr": "Antigua-et-Barbuda",
        "it": "Antigua e Barbuda",
        "pt": "Antígua e Barbuda",
        "ru": "Антигуа и Барбуда",
        "tr": "Antigua ve Barbuda",
        "zh": "安提瓜和巴布达",
        "ja": "アンティグア・バーブーダ"
    },
    "Argentina": {
        "de": "Argentinien",
        "en": "Argentina",
        "pl": "Argentyna",
        "es": "Argentina",
        "fr": "Argentine",
        "it": "Argentina",
        "pt": "Argentina",
        "ru": "Аргентина",
        "tr": "Arjantin",
        "zh": "阿根廷",
        "ja": "アルゼンチン"
    },
    "Armenia": {
        "de": "Armenien",
        "en": "Armenia",
        "pl": "Armenia",
        "es": "Armenia",
        "fr": "Arménie",
        "it": "Armenia",
        "pt": "Armênia",
        "ru": "Армения",
        "tr": "Ermenistan",
        "zh": "亚美尼亚",
        "ja": "アルメニア"
    },
    "Aruba": {
        "de": "Aruba",
        "en": "Aruba",
        "pl": "Aruba",
        "es": "Aruba",
        "fr": "Aruba",
        "it": "Aruba",
        "pt": "Aruba",
        "ru": "Аруба",
        "tr": "Aruba",
        "zh": "阿鲁巴",
        "ja": "アルバ"
    },
    "Australia": {
        "de": "Australien",
        "en": "Australia",
        "pl": "Australia",
        "es": "Australia",
        "fr": "Australie",
        "it": "Australia",
        "pt": "Austrália",
        "ru": "Австралия",
        "tr": "Avustralya",
        "zh": "澳大利亚",
        "ja": "オーストラリア"
    },
    "Austria": {
        "de": "Österreich",
        "en": "Austria",
        "pl": "Austria",
        "es": "Austria",
        "fr": "Autriche",
        "it": "Austria",
        "pt": "Áustria",
        "ru": "Австрия",
        "tr": "Avusturya",
        "zh": "奥地利",
        "ja": "オーストリア"
    },
    "Azerbaijan": {
        "de": "Aserbaidschan",
        "en": "Azerbaijan",
        "pl": "Azerbejdżan",
        "es": "Azerbaiyán",
        "fr": "Azerbaïdjan",
        "it": "Azerbaigian",
        "pt": "Azerbaijão",
        "ru": "Азербайджан",
        "tr": "Azerbaycan",
        "zh": "阿塞拜疆",
        "ja": "アゼルバイジャン"
    },
    "Bahamas": {
        "de": "Bahamas",
        "en": "Bahamas",
        "pl": "Bahamy",
        "es": "Bahamas",
        "fr": "Bahamas",
        "it": "Bahamas",
        "pt": "Bahamas",
        "ru": "Багамы",
        "tr": "Bahamalar",
        "zh": "巴哈马",
        "ja": "バハマ"
    },
    "Bahrain": {
        "de": "Bahrain",
        "en": "Bahrain",
        "pl": "Bahrajn",
        "es": "Baréin",
        "fr": "Bahreïn",
        "it": "Bahrein",
        "pt": "Bahrein",
        "ru": "Бахрейн",
        "tr": "Bahreyn",
        "zh": "巴林",
        "ja": "バーレーン"
    },
    "Bangladesh": {
        "de": "Bangladesch",
        "en": "Bangladesh",
        "pl": "Bangladesz",
        "es": "Bangladés",
        "fr": "Bangladesh",
        "it": "Bangladesh",
        "pt": "Bangladesh",
        "ru": "Бангладеш",
        "tr": "Bangladeş",
        "zh": "孟加拉国",
        "ja": "バングラデシュ"
    },
    "Barbados": {
        "de": "Barbados",
        "en": "Barbados",
        "pl": "Barbados",
        "es": "Barbados",
        "fr": "Barbade",
        "it": "Barbados",
        "pt": "Barbados",
        "ru": "Барбадос",
        "tr": "Barbados",
        "zh": "巴巴多斯",
        "ja": "バルバドス"
    },
    "Belarus": {
        "de": "Weißrussland",
        "en": "Belarus",
        "pl": "Białoruś",
        "es": "Bielorrusia",
        "fr": "Biélorussie",
        "it": "Bielorussia",
        "pt": "Bielorrússia",
        "ru": "Беларусь",
        "tr": "Belarus",
        "zh": "白俄罗斯",
        "ja": "ベラルーシ"
    },
    "Belgium": {
        "de": "Belgien",
        "en": "Belgium",
        "pl": "Belgia",
        "es": "Bélgica",
        "fr": "Belgique",
        "it": "Belgio",
        "pt": "Bélgica",
        "ru": "Бельгия",
        "tr": "Belçika",
        "zh": "比利时",
        "ja": "ベルギー"
    },
    "Belize": {
        "de": "Belize",
        "en": "Belize",
        "pl": "Belize",
        "es": "Belice",
        "fr": "Belize",
        "it": "Belize",
        "pt": "Belize",
        "ru": "Белиз",
        "tr": "Belize",
        "zh": "伯利兹",
        "ja": "ベリーズ"
    },
    "Benin": {
        "de": "Benin",
        "en": "Benin",
        "pl": "Benin",
        "es": "Benín",
        "fr": "Bénin",
        "it": "Benin",
        "pt": "Benim",
        "ru": "Бенин",
        "tr": "Benin",
        "zh": "贝宁",
        "ja": "ベナン"
    },
    "Bermuda": {
        "de": "Bermuda",
        "en": "Bermuda",
        "pl": "Bermudy",
        "es": "Bermudas",
        "fr": "Bermudes",
        "it": "Bermuda",
        "pt": "Bermudas",
        "ru": "Бермуды",
        "tr": "Bermuda",
        "zh": "百慕大",
        "ja": "バミューダ"
    },
    "Bhutan": {
        "de": "Bhutan",
        "en": "Bhutan",
        "pl": "Bhutan",
        "es": "Bután",
        "fr": "Bhoutan",
        "it": "Bhutan",
        "pt": "Butão",
        "ru": "Бутан",
        "tr": "Butan",
        "zh": "不丹",
        "ja": "ブータン"
    },
    "Bolivia, Plurinational State of": {
        "de": "Bolivien",
        "en": "Bolivia",
        "pl": "Boliwia",
        "es": "Bolivia",
        "fr": "Bolivie",
        "it": "Bolivia",
        "pt": "Bolívia",
        "ru": "Боливия",
        "tr": "Bolivya",
        "zh": "玻利维亚",
        "ja": "ボリビア"
    },
    "Bosnia and Herzegovina": {
        "de": "Bosnien und Herzegowina",
        "en": "Bosnia and Herzegovina",
        "pl": "Bośnia i Hercegowina",
        "es": "Bosnia y Herzegovina",
        "fr": "Bosnie-Herzégovine",
        "it": "Bosnia ed Erzegovina",
        "pt": "Bósnia e Herzegovina",
        "ru": "Босния и Герцеговина",
        "tr": "Bosna Hersek",
        "zh": "波斯尼亚和黑塞哥维那",
        "ja": "ボスニア・ヘルツェゴビナ"
    },
    "Botswana": {
        "de": "Botswana",
        "en": "Botswana",
        "pl": "Botswana",
        "es": "Botsuana",
        "fr": "Botswana",
        "it": "Botswana",
        "pt": "Botsuana",
        "ru": "Ботсвана",
        "tr": "Botsvana",
        "zh": "博茨瓦纳",
        "ja": "ボツワナ"
    },
    "Bouvet Island": {
        "de": "Bouvetinsel",
        "en": "Bouvet Island",
        "pl": "Wyspa Bouveta",
        "es": "Isla Bouvet",
        "fr": "Île Bouvet",
        "it": "Isola Bouvet",
        "pt": "Ilha Bouvet",
        "ru": "Остров Буве",
        "tr": "Bouvet Adası",
        "zh": "布韦岛",
        "ja": "ブーベ島"
    },
    "Brazil": {
        "de": "Brasilien",
        "en": "Brazil",
        "pl": "Brazylia",
        "es": "Brasil",
        "fr": "Brésil",
        "it": "Brasile",
        "pt": "Brasil",
        "ru": "Бразилия",
        "tr": "Brezilya",
        "zh": "巴西",
        "ja": "ブラジル"
    },
    "British Indian Ocean Territory": {
        "de": "Britisches Territorium im Indischen Ozean",
        "en": "British Indian Ocean Territory",
        "pl": "Brytyjskie Terytorium Oceanu Indyjskiego",
        "es": "Territorio Británico del Océano Índico",
        "fr": "Territoire britannique de l'océan Indien",
        "it": "Territorio britannico dell'Oceano Indiano",
        "pt": "Território Britânico do Oceano Índico",
        "ru": "Британская территория в Индийском океане",
        "tr": "Britanya Hint Okyanusu Toprakları",
        "zh": "英属印度洋领地",
        "ja": "イギリス領インド洋地域"
    },
    "Brunei Darussalam": {
        "de": "Brunei Darussalam",
        "en": "Brunei Darussalam",
        "pl": "Brunei",
        "es": "Brunéi",
        "fr": "Brunei Darussalam",
        "it": "Brunei Darussalam",
        "pt": "Brunei",
        "ru": "Бруней-Даруссалам",
        "tr": "Brunei",
        "zh": "文莱达鲁萨兰国",
        "ja": "ブルネイ・ダルサラーム"
    },
    "Bulgaria": {
        "de": "Bulgarien",
        "en": "Bulgaria",
        "pl": "Bułgaria",
        "es": "Bulgaria",
        "fr": "Bulgarie",
        "it": "Bulgaria",
        "pt": "Bulgária",
        "ru": "Болгария",
        "tr": "Bulgaristan",
        "zh": "保加利亚",
        "ja": "ブルガリア"
    },
    "Burkina Faso": {
        "de": "Burkina Faso",
        "en": "Burkina Faso",
        "pl": "Burkina Faso",
        "es": "Burkina Faso",
        "fr": "Burkina Faso",
        "it": "Burkina Faso",
        "pt": "Burkina Faso",
        "ru": "Буркина-Фасо",
        "tr": "Burkina Faso",
        "zh": "布基纳法索",
        "ja": "ブルキナファソ"
    },
    "Burundi": {
        "de": "Burundi",
        "en": "Burundi",
        "pl": "Burundi",
        "es": "Burundi",
        "fr": "Burundi",
        "it": "Burundi",
        "pt": "Burundi",
        "ru": "Бурунди",
        "tr": "Burundi",
        "zh": "布隆迪",
        "ja": "ブルンジ"
    },
    "Cabo Verde": {
        "de": "Kap Verde",
        "en": "Cape Verde",
        "pl": "Republika Zielonego Przylądka",
        "es": "Cabo Verde",
        "fr": "Cap-Vert",
        "it": "Capo Verde",
        "pt": "Cabo Verde",
        "ru": "Кабо-Верде",
        "tr": "Yeşil Burun Adaları",
        "zh": "佛得角",
        "ja": "カーボベルデ"
    },
    "Cambodia": {
        "de": "Kambodscha",
        "en": "Cambodia",
        "pl": "Kambodża",
        "es": "Camboya",
        "fr": "Cambodge",
        "it": "Cambogia",
        "pt": "Camboja",
        "ru": "Камбоджа",
        "tr": "Kamboçya",
        "zh": "柬埔寨",
        "ja": "カンボジア"
    },
    "Cameroon": {
        "de": "Kamerun",
        "en": "Cameroon",
        "pl": "Kamerun",
        "es": "Camerún",
        "fr": "Cameroun",
        "it": "Camerun",
        "pt": "Camarões",
        "ru": "Камерун",
        "tr": "Kamerun",
        "zh": "喀麦隆",
        "ja": "カメルーン"
    },
    "Canada": {
        "de": "Kanada",
        "en": "Canada",
        "pl": "Kanada",
        "es": "Canadá",
        "fr": "Canada",
        "it": "Canada",
        "pt": "Canadá",
        "ru": "Канада",
        "tr": "Kanada",
        "zh": "加拿大",
        "ja": "カナダ"
    },
    "Caribbean Netherlands": {
        "de": "Karibische Niederlande",
        "en": "Caribbean Netherlands",
        "pl": "Karibskie Niderlandy",
        "es": "Países Bajos Caribeños",
        "fr": "Pays-Bas caribéens",
        "it": "Paesi Bassi caraibici",
        "pt": "Países Baixos Caribenhos",
        "ru": "Карибские Нидерланды",
        "tr": "Karayip Hollanda",
        "zh": "加勒比荷兰",
        "ja": "カリブ海オランダ"
    },
    "Cayman Islands": {
        "de": "Kaimaninseln",
        "en": "Cayman Islands",
        "pl": "Kajmany",
        "es": "Islas Caimán",
        "fr": "Îles Caïmans",
        "it": "Isole Cayman",
        "pt": "Ilhas Cayman",
        "ru": "Каймановы острова",
        "tr": "Cayman Adaları",
        "zh": "开曼群岛",
        "ja": "ケイマン諸島"
    },
    "Central African Republic": {
        "de": "Zentralafrikanische Republik",
        "en": "Central African Republic",
        "pl": "Republika Środkowoafrykańska",
        "es": "República Centroafricana",
        "fr": "République centrafricaine",
        "it": "Repubblica Centrafricana",
        "pt": "República Centro-Africana",
        "ru": "Центральноафриканская Республика",
        "tr": "Orta Afrika Cumhuriyeti",
        "zh": "中非共和国",
        "ja": "中央アフリカ共和国"
    },
    "Chad": {
        "de": "Tschad",
        "en": "Chad",
        "pl": "Czad",
        "es": "Chad",
        "fr": "Tchad",
        "it": "Ciad",
        "pt": "Chade",
        "ru": "Чад",
        "tr": "Çad",
        "zh": "乍得",
        "ja": "チャド"
    },
    "Chile": {
        "de": "Chile",
        "en": "Chile",
        "pl": "Chile",
        "es": "Chile",
        "fr": "Chili",
        "it": "Cile",
        "pt": "Chile",
        "ru": "Чили",
        "tr": "Şili",
        "zh": "智利",
        "ja": "チリ"
    },
    "China (People's Republic of China)": {
        "de": "China",
        "en": "China",
        "pl": "Chiny",
        "es": "China",
        "fr": "Chine",
        "it": "Cina",
        "pt": "China",
        "ru": "Китай",
        "tr": "Çin",
        "zh": "中国",
        "ja": "中国"
    },
    "Christmas Island": {
        "de": "Weihnachtsinsel",
        "en": "Christmas Island",
        "pl": "Wyspa Bożego Narodzenia",
        "es": "Isla de Navidad",
        "fr": "Île Christmas",
        "it": "Isola di Natale",
        "pt": "Ilha do Natal",
        "ru": "Остров Рождества",
        "tr": "Christmas Adası",
        "zh": "圣诞岛",
        "ja": "クリスマス島"
    },
    "Cocos (Keeling) Islands": {
        "de": "Kokosinseln",
        "en": "Cocos (Keeling) Islands",
        "pl": "Wyspy Kokosowe",
        "es": "Islas Cocos (Keeling)",
        "fr": "Îles Cocos (Keeling)",
        "it": "Isole Cocos (Keeling)",
        "pt": "Ilhas Cocos (Keeling)",
        "ru": "Кокосовые острова",
        "tr": "Cocos (Keeling) Adaları",
        "zh": "科科斯（基林）群岛",
        "ja": "ココス（キーリング）諸島"
    },
    "Colombia": {
        "de": "Kolumbien",
        "en": "Colombia",
        "pl": "Kolumbia",
        "es": "Colombia",
        "fr": "Colombie",
        "it": "Colombia",
        "pt": "Colômbia",
        "ru": "Колумбия",
        "tr": "Kolombiya",
        "zh": "哥伦比亚",
        "ja": "コロンビア"
    },
    "Comoros": {
        "de": "Komoren",
        "en": "Comoros",
        "pl": "Komory",
        "es": "Comoras",
        "fr": "Comores",
        "it": "Comore",
        "pt": "Comores",
        "ru": "Коморские острова",
        "tr": "Komorlar",
        "zh": "科摩罗",
        "ja": "コモロ"
    },
    "Congo, the Democratic Republic of the": {
        "de": "Kongo",
        "en": "Congo",
        "pl": "Kongo",
        "es": "Congo",
        "fr": "Congo",
        "it": "Congo",
        "pt": "Congo",
        "ru": "Конго",
        "tr": "Kongo",
        "zh": "刚果（金）",
        "ja": "コンゴ民主共和国"
    },
    "Cook Islands": {
        "de": "Cookinseln",
        "en": "Cook Islands",
        "pl": "Wyspy Cooka",
        "es": "Islas Cook",
        "fr": "Îles Cook",
        "it": "Isole Cook",
        "pt": "Ilhas Cook",
        "ru": "Острова Кука",
        "tr": "Cook Adaları",
        "zh": "库克群岛",
        "ja": "クック諸島"
    },
    "Costa Rica": {
        "de": "Costa Rica",
        "en": "Costa Rica",
        "pl": "Kostaryka",
        "es": "Costa Rica",
        "fr": "Costa Rica",
        "it": "Costa Rica",
        "pt": "Costa Rica",
        "ru": "Коста-Рика",
        "tr": "Kosta Rika",
        "zh": "哥斯达黎加",
        "ja": "コスタリカ"
    },
    "Cote d'Ivoire":{
        "de": "Elfenbeinküste",
        "en": "Cote d'Ivoire",
        "pl": "Wybrzeże Kości Słoniowej",
        "es": "Costa de Marfil",
        "fr": "Côte d'Ivoire",
        "it": "Costa d'Avorio",
        "pt": "Costa do Marfim",
        "ru": "Кот-д'Ивуар",
        "tr": "Fildişi Sahili",
        "zh": "科特迪瓦",
        "ja": "コートジボワール"
    },
    "Croatia": {
        "de": "Kroatien",
        "en": "Croatia",
        "pl": "Chorwacja",
        "es": "Croacia",
        "fr": "Croatie",
        "it": "Croazia",
        "pt": "Croácia",
        "ru": "Хорватия",
        "tr": "Hırvatistan",
        "zh": "克罗地亚",
        "ja": "クロアチア"
    },
    "Cuba": {
        "de": "Kuba",
        "en": "Cuba",
        "pl": "Kuba",
        "es": "Cuba",
        "fr": "Cuba",
        "it": "Cuba",
        "pt": "Cuba",
        "ru": "Куба",
        "tr": "Küba",
        "zh": "古巴",
        "ja": "キューバ"
    },
    "Curacao": {
        "de": "Curaçao",
        "en": "Curacao",
        "pl": "Curaçao",
        "es": "Curazao",
        "fr": "Curaçao",
        "it": "Curaçao",
        "pt": "Curaçao",
        "ru": "Кюрасао",
        "tr": "Curaçao",
        "zh": "库拉索",
        "ja": "キュラソー"
    },
    "Cyprus": {
        "de": "Zypern",
        "en": "Cyprus",
        "pl": "Cypr",
        "es": "Chipre",
        "fr": "Chypre",
        "it": "Cipro",
        "pt": "Chipre",
        "ru": "Кипр",
        "tr": "Kıbrıs",
        "zh": "塞浦路斯",
        "ja": "キプロス"
    },
    "Czech Republic": {
        "de": "Tschechien",
        "en": "Czechia",
        "pl": "Czechy",
        "es": "Chequia",
        "fr": "Tchéquie",
        "it": "Cechia",
        "pt": "Chéquia",
        "ru": "Чехия",
        "tr": "Çekya",
        "zh": "捷克",
        "ja": "チェコ"
    },
    "Denmark": {
        "de": "Dänemark",
        "en": "Denmark",
        "pl": "Dania",
        "es": "Dinamarca",
        "fr": "Danemark",
        "it": "Danimarca",
        "pt": "Dinamarca",
        "ru": "Дания",
        "tr": "Danimarka",
        "zh": "丹麦",
        "ja": "デンマーク"
    },
    "Djibouti": {
        "de": "Dschibuti",
        "en": "Djibouti",
        "pl": "Dżibuti",
        "es": "Yibuti",
        "fr": "Djibouti",
        "it": "Gibuti",
        "pt": "Djibuti",
        "ru": "Джибути",
        "tr": "Cibuti",
        "zh": "吉布提",
        "ja": "ジブチ"
    },
    "Dominica": {
        "de": "Dominica",
        "en": "Dominica",
        "pl": "Dominika",
        "es": "Dominica",
        "fr": "Dominique",
        "it": "Dominica",
        "pt": "Dominica",
        "ru": "Доминика",
        "tr": "Dominika",
        "zh": "多米尼加",
        "ja": "ドミニカ"
    },
    "Dominican Republic": {
        "de": "Dominikanische Republik",
        "en": "Dominican Republic",
        "pl": "Republika Dominikany",
        "es": "República Dominicana",
        "fr": "République dominicaine",
        "it": "Repubblica Dominicana",
        "pt": "República Dominicana",
        "ru": "Доминиканская Республика",
        "tr": "Dominik Cumhuriyeti",
        "zh": "多米尼加共和国",
        "ja": "ドミニカ共和国"
    },
    "Ecuador": {
        "de": "Ecuador",
        "en": "Ecuador",
        "pl": "Ekwador",
        "es": "Ecuador",
        "fr": "Équateur",
        "it": "Ecuador",
        "pt": "Equador",
        "ru": "Эквадор",
        "tr": "Ekvador",
        "zh": "厄瓜多尔",
        "ja": "エクアドル"
    },
    "Egypt": {
        "de": "Ägypten",
        "en": "Egypt",
        "pl": "Egipt",
        "es": "Egipto",
        "fr": "Égypte",
        "it": "Egitto",
        "pt": "Egito",
        "ru": "Египет",
        "tr": "Mısır",
        "zh": "埃及",
        "ja": "エジプト"
    },
    "El Salvador": {
        "de": "El Salvador",
        "en": "El Salvador",
        "pl": "Salwador",
        "es": "El Salvador",
        "fr": "Salvador",
        "it": "El Salvador",
        "pt": "El Salvador",
        "ru": "Сальвадор",
        "tr": "El Salvador",
        "zh": "萨尔瓦多",
        "ja": "エルサルバドル"
    },
    "England": {
        "de": "England",
        "en": "England",
        "pl": "Anglia",
        "es": "Inglaterra",
        "fr": "Angleterre",
        "it": "Inghilterra",
        "pt": "Inglaterra",
        "ru": "Англия",
        "tr": "İngiltere",
        "zh": "英格兰",
        "ja": "イングランド"
    },
    "Equatorial Guinea": {
        "de": "Äquatorialguinea",
        "en": "Equatorial Guinea",
        "pl": "Gwinea Równikowa",
        "es": "Guinea Ecuatorial",
        "fr": "Guinée équatoriale",
        "it": "Guinea Equatoriale",
        "pt": "Guiné Equatorial",
        "ru": "Экваториальная Гвинея",
        "tr": "Ekvator Ginesi",
        "zh": "赤道几内亚",
        "ja": "赤道ギニア"
    },
    "Eritrea": {
        "de": "Eritrea",
        "en": "Eritrea",
        "pl": "Erytrea",
        "es": "Eritrea",
        "fr": "Érythrée",
        "it": "Eritrea",
        "pt": "Eritreia",
        "ru": "Эритрея",
        "tr": "Eritre",
        "zh": "厄立特里亚",
        "ja": "エリトリア"
    },
    "Estonia": {
        "de": "Estland",
        "en": "Estonia",
        "pl": "Estonia",
        "es": "Estonia",
        "fr": "Estonie",
        "it": "Estonia",
        "pt": "Estônia",
        "ru": "Эстония",
        "tr": "Estonya",
        "zh": "爱沙尼亚",
        "ja": "エストニア"
    },
    "Eswatini": {
        "de": "Eswatini",
        "en": "Eswatini",
        "pl": "Eswatini",
        "es": "Esuatini",
        "fr": "Eswatini",
        "it": "Eswatini",
        "pt": "Eswatini",
        "ru": "Эсватини",
        "tr": "Eswatini",
        "zh": "斯威士兰",
        "ja": "エスワティニ"
    },
    "Ethiopia": {
        "de": "Äthiopien",
        "en": "Ethiopia",
        "pl": "Etiopia",
        "es": "Etiopía",
        "fr": "Éthiopie",
        "it": "Etiopia",
        "pt": "Etiópia",
        "ru": "Эфиопия",
        "tr": "Etiyopya",
        "zh": "埃塞俄比亚",
        "ja": "エチオピア"
    },
    "Europe": {
        "de": "Europa",
        "en": "Europe",
        "pl": "Europa",
        "es": "Europa",
        "fr": "Europe",
        "it": "Europa",
        "pt": "Europa",
        "ru": "Европа",
        "tr": "Avrupa",
        "zh": "欧洲",
        "ja": "ヨーロッパ"
    },
    "Falkland Islands (Malvinas)": {
        "de": "Falklandinseln",
        "en": "Falkland Islands",
        "pl": "Falklandy",
        "es": "Islas Malvinas",
        "fr": "Îles Malouines",
        "it": "Isole Falkland",
        "pt": "Ilhas Malvinas",
        "ru": "Фолклендские острова",
        "tr": "Falkland Adaları",
        "zh": "福克兰群岛",
        "ja": "フォークランド（マルビナス）諸島"
    },
    "Faroe Islands": {
        "de": "Färöer",
        "en": "Faroe Islands",
        "pl": "Wyspy Owcze",
        "es": "Islas Feroe",
        "fr": "Îles Féroé",
        "it": "Isole Faroe",
        "pt": "Ilhas Faroé",
        "ru": "Фарерские острова",
        "tr": "Faroe Adaları",
        "zh": "法罗群岛",
        "ja": "フェロー諸島"
    },
    "Fiji": {
        "de": "Fidschi",
        "en": "Fiji",
        "pl": "Fidżi",
        "es": "Fiyi",
        "fr": "Fidji",
        "it": "Figi",
        "pt": "Fiji",
        "ru": "Фиджи",
        "tr": "Fiji",
        "zh": "斐济",
        "ja": "フィジー"
    },
    "Finland": {
        "de": "Finnland",
        "en": "Finland",
        "pl": "Finlandia",
        "es": "Finlandia",
        "fr": "Finlande",
        "it": "Finlandia",
        "pt": "Finlândia",
        "ru": "Финляндия"
    },
    "France": {
        "de": "Frankreich",
        "en": "France",
        "pl": "Francja",
        "es": "Francia",
        "fr": "France",
        "it": "Francia",
        "pt": "França",
        "ru": "Франция",
        "tr": "Fransa",
        "zh": "法国",
        "ja": "フランス"
    },
    "French Guiana": {
        "de": "Französisch-Guayana",
        "en": "French Guiana",
        "pl": "Gujana Francuska",
        "es": "Guayana Francesa",
        "fr": "Guyane française",
        "it": "Guyana francese",
        "pt": "Guiana Francesa",
        "ru": "Французская Гвиана",
        "tr": "Fransız Guyanası",
        "zh": "法属圭亚那",
        "ja": "フランス領ギアナ"
    },
    "French Polynesia": {
        "de": "Französisch-Polynesien",
        "en": "French Polynesia",
        "pl": "Polinezja Francuska",
        "es": "Polinesia Francesa",
        "fr": "Polynésie française",
        "it": "Polinesia francese",
        "pt": "Polinésia Francesa",
        "ru": "Французская Полинезия",
        "tr": "Fransız Polinezyası",
        "zh": "法属波利尼西亚",
        "ja": "フランス領ポリネシア"
    },
    "French Southern Territories": {
        "de": "Französische Süd- und Antarktisgebiete",
        "en": "French Southern Territories",
        "pl": "Francuskie Terytoria Południowe i Antarktyczne",
        "es": "Tierras Australes Francesas",
        "fr": "Terres australes françaises",
        "it": "Territori Francesi del Sud",
        "pt": "Territórios Franceses do Sul",
        "ru": "Французские Южные территории",
        "tr": "Fransız Güney ve Antarktika Toprakları",
        "zh": "法属南部领地",
        "ja": "フランス領南方・南極地域"
    },
    "Gabon": {
        "de": "Gabun",
        "en": "Gabon",
        "pl": "Gabon",
        "es": "Gabón",
        "fr": "Gabon",
        "it": "Gabon",
        "pt": "Gabão",
        "ru": "Габон",
        "tr": "Gabon",
        "zh": "加蓬",
        "ja": "ガボン"
    },
    "Gambia": {
        "de": "Gambia",
        "en": "Gambia",
        "pl": "Gambia",
        "es": "Gambia",
        "fr": "Gambie",
        "it": "Gambia",
        "pt": "Gâmbia",
        "ru": "Гамбия",
        "tr": "Gambiya",
        "zh": "冈比亚",
        "ja": "ガンビア"
    },
    "Georgia": {
        "de": "Georgien",
        "en": "Georgia",
        "pl": "Gruzja",
        "es": "Georgia",
        "fr": "Géorgie",
        "it": "Georgia",
        "pt": "Geórgia",
        "ru": "Грузия",
        "tr": "Gürcistan",
        "zh": "格鲁吉亚",
        "ja": "ジョージア"
    },
    "Germany": {
        "de": "Deutschland",
        "en": "Germany",
        "pl": "Niemcy",
        "es": "Alemania",
        "fr": "Allemagne",
        "it": "Germania",
        "pt": "Alemanha",
        "ru": "Германия",
        "tr": "Almanya",
        "zh": "德国",
        "ja": "ドイツ"
    },
    "Ghana": {
        "de": "Ghana",
        "en": "Ghana",
        "pl": "Ghana",
        "es": "Ghana",
        "fr": "Ghana",
        "it": "Ghana",
        "pt": "Gana",
        "ru": "Гана",
        "tr": "Gana",
        "zh": "加纳",
        "ja": "ガーナ"
    },
    "Gibraltar": {
        "de": "Gibraltar",
        "en": "Gibraltar",
        "pl": "Gibraltar",
        "es": "Gibraltar",
        "fr": "Gibraltar",
        "it": "Gibilterra",
        "pt": "Gibraltar",
        "ru": "Гибралтар",
        "tr": "Cebelitarık",
        "zh": "直布罗陀",
        "ja": "ジブラルタル"
    },
    "Greece": {
        "de": "Griechenland",
        "en": "Greece",
        "pl": "Grecja",
        "es": "Grecia",
        "fr": "Grèce",
        "it": "Grecia",
        "pt": "Grécia",
        "ru": "Греция",
        "tr": "Yunanistan",
        "zh": "希腊",
        "ja": "ギリシャ"
    },
    "Greenland": {
        "de": "Grönland",
        "en": "Greenland",
        "pl": "Grenlandia",
        "es": "Groenlandia",
        "fr": "Groenland",
        "it": "Groenlandia",
        "pt": "Gronelândia",
        "ru": "Гренландия",
        "tr": "Grönland",
        "zh": "格陵兰",
        "ja": "グリーンランド"
    },
    "Grenada": {
        "de": "Grenada",
        "en": "Grenada",
        "pl": "Grenada",
        "es": "Granada",
        "fr": "Grenade",
        "it": "Grenada",
        "pt": "Granada",
        "ru": "Гренада",
        "tr": "Grenada",
        "zh": "格林纳达",
        "ja": "グレナダ"
    },
    "Guadeloupe": {
        "de": "Guadeloupe",
        "en": "Guadeloupe",
        "pl": "Gwadelupa",
        "es": "Guadalupe",
        "fr": "Guadeloupe",
        "it": "Guadalupa",
        "pt": "Guadalupe",
        "ru": "Гваделупа",
        "tr": "Guadeloupe",
        "zh": "瓜德罗普",
        "ja": "グアドループ"
    },
    "Guam": {
        "de": "Guam",
        "en": "Guam",
        "pl": "Guam",
        "es": "Guam",
        "fr": "Guam",
        "it": "Guam",
        "pt": "Guam",
        "ru": "Гуам",
        "tr": "Guam",
        "zh": "关岛",
        "ja": "グアム"
    },
    "Guatemala": {
        "de": "Guatemala",
        "en": "Guatemala",
        "pl": "Gwatemala",
        "es": "Guatemala",
        "fr": "Guatemala",
        "it": "Guatemala",
        "pt": "Guatemala",
        "ru": "Гватемала",
        "tr": "Guatemala",
        "zh": "危地马拉",
        "ja": "グアテマラ"
    },
    "Guernsey": {
        "de": "Guernsey",
        "en": "Guernsey",
        "pl": "Guernsey",
        "es": "Guernesey",
        "fr": "Guernesey",
        "it": "Guernsey",
        "pt": "Guernsey",
        "ru": "Гернси",
        "tr": "Guernsey",
        "zh": "根西岛",
        "ja": "ガーンジー"
    },
    "Guinea": {
        "de": "Guinea",
        "en": "Guinea",
        "pl": "Gwinea",
        "es": "Guinea",
        "fr": "Guinée",
        "it": "Guinea",
        "pt": "Guiné",
        "ru": "Гвинея",
        "tr": "Gine",
        "zh": "几内亚",
        "ja": "ギニア"
    },
    "Guinea-Bissau": {
        "de": "Guinea-Bissau",
        "en": "Guinea-Bissau",
        "pl": "Gwinea Bissau",
        "es": "Guinea-Bisáu",
        "fr": "Guinée-Bissau",
        "it": "Guinea-Bissau",
        "pt": "Guiné-Bissau",
        "ru": "Гвинея-Бисау",
        "tr": "Gine-Bissau",
        "zh": "几内亚比绍",
        "ja": "ギニアビサウ"
    },
    "Guyana": {
        "de": "Guyana",
        "en": "Guyana",
        "pl": "Gujana",
        "es": "Guyana",
        "fr": "Guyane",
        "it": "Guyana",
        "pt": "Guiana",
        "ru": "Гайана",
        "tr": "Guyana",
        "zh": "圭亚那",
        "ja": "ガイアナ"
    },
    "Haiti": {
        "de": "Haiti",
        "en": "Haiti",
        "pl": "Haiti",
        "es": "Haití",
        "fr": "Haïti",
        "it": "Haiti",
        "pt": "Haiti",
        "ru": "Гаити",
        "tr": "Haiti",
        "zh": "海地",
        "ja": "ハイチ"
    },
    "Heard Island and McDonald Islands": {
        "de": "Heard- und McDonaldinseln",
        "en": "Heard Island and McDonald Islands",
        "pl": "Wyspy Heard i McDonalda",
        "es": "Isla Heard y Islas McDonald",
        "fr": "Île Heard et îles McDonald",
        "it": "Isole Heard e McDonald",
        "pt": "Ilha Heard e Ilhas McDonald",
        "ru": "Остров Херд и острова Макдональд",
        "tr": "Heard Adası ve McDonald Adaları",
        "zh": "赫德岛和麦克唐纳群岛",
        "ja": "ハード島とマクドナルド諸島"
    },
    "Holy See (Vatican City State)": {
        "de": "Vatikanstadt",
        "en": "Holy See",
        "pl": "Watykan",
        "es": "Ciudad del Vaticano",
        "fr": "Saint-Siège",
        "it": "Città del Vaticano",
        "pt": "Vaticano",
        "ru": "Ватикан",
        "tr": "Vatikan",
        "zh": "梵蒂冈",
        "ja": "バチカン市国"
    },
    "Honduras": {
        "de": "Honduras",
        "en": "Honduras",
        "pl": "Honduras",
        "es": "Honduras",
        "fr": "Honduras",
        "it": "Honduras",
        "pt": "Honduras",
        "ru": "Гондурас",
        "tr": "Honduras",
        "zh": "洪都拉斯",
        "ja": "ホンジュラス"
    },
    "Hong Kong": {
        "de": "Hongkong",
        "en": "Hong Kong",
        "pl": "Hongkong",
        "es": "Hong Kong",
        "fr": "Hong Kong",
        "it": "Hong Kong",
        "pt": "Hong Kong",
        "ru": "Гонконг",
        "tr": "Hong Kong",
        "zh": "香港",
        "ja": "香港"
    },
    "Hungary": {
        "de": "Ungarn",
        "en": "Hungary",
        "pl": "Węgry",
        "es": "Hungría",
        "fr": "Hongrie",
        "it": "Ungheria",
        "pt": "Hungria",
        "ru": "Венгрия",
        "tr": "Macaristan",
        "zh": "匈牙利",
        "ja": "ハンガリー"
    },
    "Iceland": {
        "de": "Island",
        "en": "Iceland",
        "pl": "Islandia",
        "es": "Islandia",
        "fr": "Islande",
        "it": "Islanda",
        "pt": "Islândia",
        "ru": "Исландия",
        "tr": "İzlanda",
        "zh": "冰岛",
        "ja": "アイスランド"
    },
    "India": {
        "de": "Indien",
        "en": "India",
        "pl": "Indie",
        "es": "India",
        "fr": "Inde",
        "it": "India",
        "pt": "Índia",
        "ru": "Индия",
        "tr": "Hindistan",
        "zh": "印度",
        "ja": "インド"
    },
    "Indonesia": {
        "de": "Indonesien",
        "en": "Indonesia",
        "pl": "Indonezja",
        "es": "Indonesia",
        "fr": "Indonésie",
        "it": "Indonesia",
        "pt": "Indonésia",
        "ru": "Индонезия",
        "tr": "Endonezya",
        "zh": "印度尼西亚",
        "ja": "インドネシア"
    },
    "Iran, Islamic Republic of": {
        "de": "Iran",
        "en": "Iran",
        "pl": "Iran",
        "es": "Irán",
        "fr": "Iran",
        "it": "Iran",
        "pt": "Irão",
        "ru": "Иран",
        "tr": "İran",
        "zh": "伊朗",
        "ja": "イラン"
    },
    "Iraq": {
        "de": "Irak",
        "en": "Iraq",
        "pl": "Irak",
        "es": "Irak",
        "fr": "Irak",
        "it": "Iraq",
        "pt": "Iraque",
        "ru": "Ирак",
        "tr": "Irak",
        "zh": "伊拉克",
        "ja": "イラク"
    },
    "Ireland": {
        "de": "Irland",
        "en": "Ireland",
        "pl": "Irlandia",
        "es": "Irlanda",
        "fr": "Irlande",
        "it": "Irlanda",
        "pt": "Irlanda",
        "ru": "Ирландия",
        "tr": "İrlanda",
        "zh": "爱尔兰",
        "ja": "アイルランド"
    },
    "Isle of Man": {
        "de": "Insel Man",
        "en": "Isle of Man",
        "pl": "Wyspa Man",
        "es": "Isla de Man",
        "fr": "Île de Man",
        "it": "Isola di Man",
        "pt": "Ilha de Man",
        "ru": "Остров Мэн",
        "tr": "Man Adası",
        "zh": "马恩岛",
        "ja": "マン島"
    },
    "Israel": {
        "de": "Israel",
        "en": "Israel",
        "pl": "Izrael",
        "es": "Israel",
        "fr": "Israël",
        "it": "Israele",
        "pt": "Israel",
        "ru": "Израиль",
        "tr": "İsrail",
        "zh": "以色列",
        "ja": "イスラエル"
    },
    "Italy": {
        "de": "Italien",
        "en": "Italy",
        "pl": "Włochy",
        "es": "Italia",
        "fr": "Italie",
        "it": "Italia",
        "pt": "Itália",
        "ru": "Италия",
        "tr": "İtalya",
        "zh": "意大利",
        "ja": "イタリア"
    },
    "Jamaica": {
        "de": "Jamaika",
        "en": "Jamaica",
        "pl": "Jamajka",
        "es": "Jamaica",
        "fr": "Jamaïque",
        "it": "Giamaica",
        "pt": "Jamaica",
        "ru": "Ямайка",
        "tr": "Jamaika",
        "zh": "牙买加",
        "ja": "ジャマイカ"
    },
    "Japan": {
        "de": "Japan",
        "en": "Japan",
        "pl": "Japonia",
        "es": "Japón",
        "fr": "Japon",
        "it": "Giappone",
        "pt": "Japão",
        "ru": "Япония",
        "tr": "Japonya",
        "zh": "日本",
        "ja": "日本"
    },
    "Jersey": {
        "de": "Jersey",
        "en": "Jersey",
        "pl": "Jersey",
        "es": "Jersey",
        "fr": "Jersey",
        "it": "Jersey",
        "pt": "Jersey",
        "ru": "Джерси",
        "tr": "Jersey",
        "zh": "泽西岛",
        "ja": "ジャージー"
    },
    "Jordan": {
        "de": "Jordanien",
        "en": "Jordan",
        "pl": "Jordania",
        "es": "Jordania",
        "fr": "Jordanie",
        "it": "Giordania",
        "pt": "Jordânia",
        "ru": "Иордания",
        "tr": "Ürdün",
        "zh": "约旦",
        "ja": "ヨルダン"
    },
    "Kazakhstan": {
        "de": "Kasachstan",
        "en": "Kazakhstan",
        "pl": "Kazachstan",
        "es": "Kazajistán",
        "fr": "Kazakhstan",
        "it": "Kazakistan",
        "pt": "Cazaquistão",
        "ru": "Казахстан",
        "tr": "Kazakistan",
        "zh": "哈萨克斯坦",
        "ja": "カザフスタン"
    },
    "Kenya": {
        "de": "Kenia",
        "en": "Kenya",
        "pl": "Kenia",
        "es": "Kenia",
        "fr": "Kenya",
        "it": "Kenya",
        "pt": "Quénia",
        "ru": "Кения",
        "tr": "Kenya",
        "zh": "肯尼亚",
        "ja": "ケニア"
    },
    "Kiribati": {
        "de": "Kiribati",
        "en": "Kiribati",
        "pl": "Kiribati",
        "es": "Kiribati",
        "fr": "Kiribati",
        "it": "Kiribati",
        "pt": "Quiribáti",
        "ru": "Кирибати",
        "tr": "Kiribati",
        "zh": "基里巴斯",
        "ja": "キリバス"
    },
    "Korea, Democratic People's Republic of": {
        "de": "Nordkorea",
        "en": "North Korea",
        "pl": "Korea Północna",
        "es": "Corea del Norte",
        "fr": "Corée du Nord",
        "it": "Corea del Nord",
        "pt": "Coreia do Norte",
        "ru": "Северная Корея",
        "tr": "Kuzey Kore",
        "zh": "朝鲜",
        "ja": "北朝鮮"
    },
    "Korea, Republic of": {
        "de": "Südkorea",
        "en": "South Korea",
        "pl": "Korea Południowa",
        "es": "Corea del Sur",
        "fr": "Corée du Sud",
        "it": "Corea del Sud",
        "pt": "Coreia do Sul",
        "ru": "Южная Корея",
        "tr": "Güney Kore",
        "zh": "韩国",
        "ja": "大韓民国"
    },
    "Kosovo": {
        "de": "Kosovo",
        "en": "Kosovo",
        "pl": "Kosowo",
        "es": "Kosovo",
        "fr": "Kosovo",
        "it": "Kosovo",
        "pt": "Kosovo",
        "ru": "Косово",
        "tr": "Kosova",
        "zh": "科索沃",
        "ja": "コソボ"
    },
    "Kuwait": {
        "de": "Kuwait",
        "en": "Kuwait",
        "pl": "Kuwejt",
        "es": "Kuwait",
        "fr": "Koweït",
        "it": "Kuwait",
        "pt": "Kuwait",
        "ru": "Кувейт",
        "tr": "Kuveyt",
        "zh": "科威特",
        "ja": "クウェート"
    },
    "Kyrgyzstan": {
        "de": "Kirgisistan",
        "en": "Kyrgyzstan",
        "pl": "Kirgistan",
        "es": "Kirguistán",
        "fr": "Kirghizistan",
        "it": "Kirghizistan",
        "pt": "Quirguistão",
        "ru": "Киргизия",
        "tr": "Kırgızistan",
        "zh": "吉尔吉斯斯坦",
        "ja": "キルギス"
    },
    "Laos (Lao People's Democratic Republic)": {
        "de": "Laos",
        "en": "Laos",
        "pl": "Laos",
        "es": "Laos",
        "fr": "Laos",
        "it": "Laos",
        "pt": "Laos",
        "ru": "Лаос",
        "tr": "Laos",
        "zh": "老挝",
        "ja": "ラオス"
    },
    "Latvia": {
        "de": "Lettland",
        "en": "Latvia",
        "pl": "Łotwa",
        "es": "Letonia",
        "fr": "Lettonie",
        "it": "Lettonia",
        "pt": "Letônia",
        "ru": "Латвия",
        "tr": "Letonya",
        "zh": "拉脱维亚",
        "ja": "ラトビア"
    },
    "Lebanon": {
        "de": "Libanon",
        "en": "Lebanon",
        "pl": "Liban",
        "es": "Líbano",
        "fr": "Liban",
        "it": "Libano",
        "pt": "Líbano",
        "ru": "Ливан",
        "tr": "Lübnan",
        "zh": "黎巴嫩",
        "ja": "レバノン"
    },
    "Lesotho": {
        "de": "Lesotho",
        "en": "Lesotho",
        "pl": "Lesotho",
        "es": "Lesoto",
        "fr": "Lesotho",
        "it": "Lesotho",
        "pt": "Lesoto",
        "ru": "Лесото"
    },
    "Liberia": {
        "de": "Liberia",
        "en": "Liberia",
        "pl": "Liberia",
        "es": "Liberia",
        "fr": "Libéria",
        "it": "Liberia",
        "pt": "Libéria",
        "ru": "Либерия",
        "tr": "Liberya",
        "zh": "利比里亚",
        "ja": "リベリア"
    },
    "Libya": {
        "de": "Libyen",
        "en": "Libya",
        "pl": "Libia",
        "es": "Libia",
        "fr": "Libye",
        "it": "Libia",
        "pt": "Líbia",
        "ru": "Ливия",
        "tr": "Libya",
        "zh": "利比亚",
        "ja": "リビア"
    },
    "Liechtenstein": {
        "de": "Liechtenstein",
        "en": "Liechtenstein",
        "pl": "Liechtenstein",
        "es": "Liechtenstein",
        "fr": "Liechtenstein",
        "it": "Liechtenstein",
        "pt": "Liechtenstein",
        "ru": "Лихтенштейн",
        "tr": "Lihtenştayn",
        "zh": "列支敦士登",
        "ja": "リヒテンシュタイン"
    },
    "Lithuania": {
        "de": "Litauen",
        "en": "Lithuania",
        "pl": "Litwa",
        "es": "Lituania",
        "fr": "Lituanie",
        "it": "Lituania",
        "pt": "Lituânia",
        "ru": "Литва",
        "tr": "Litvanya",
        "zh": "立陶宛",
        "ja": "リトアニア"
    },
    "Luxembourg": {
        "de": "Luxemburg",
        "en": "Luxembourg",
        "pl": "Luksemburg",
        "es": "Luxemburgo",
        "fr": "Luxembourg",
        "it": "Lussemburgo",
        "pt": "Luxemburgo",
        "ru": "Люксембург",
        "tr": "Lüksemburg",
        "zh": "卢森堡",
        "ja": "ルクセンブルク"
    },
    "Macao": {
        "de": "Macao",
        "en": "Macao",
        "pl": "Makau",
        "es": "Macao",
        "fr": "Macao",
        "it": "Macao",
        "pt": "Macau",
        "ru": "Макао",
        "tr": "Macao",
        "zh": "澳门",
        "ja": "マカオ"
    },
    "Madagascar": {
        "de": "Madagaskar",
        "en": "Madagascar",
        "pl": "Madagaskar",
        "es": "Madagascar",
        "fr": "Madagascar",
        "it": "Madagascar",
        "pt": "Madagáscar",
        "ru": "Мадагаскар",
        "tr": "Madagaskar",
        "zh": "马达加斯加",
        "ja": "マダガスカル"
    },
    "Malawi": {
        "de": "Malawi",
        "en": "Malawi",
        "pl": "Malawi",
        "es": "Malaui",
        "fr": "Malawi",
        "it": "Malawi",
        "pt": "Malawi",
        "ru": "Малави",
        "tr": "Malavi",
        "zh": "马拉维",
        "ja": "マラウイ"
    },
    "Malaysia": {
        "de": "Malaysia",
        "en": "Malaysia",
        "pl": "Malezja",
        "es": "Malasia",
        "fr": "Malaisie",
        "it": "Malesia",
        "pt": "Malásia",
        "ru": "Малайзия",
        "tr": "Malezya",
        "zh": "马来西亚",
        "ja": "マレーシア"
    },
    "Maldives": {
        "de": "Malediven",
        "en": "Maldives",
        "pl": "Malediwy",
        "es": "Maldivas",
        "fr": "Maldives",
        "it": "Maldive",
        "pt": "Maldivas",
        "ru": "Мальдивы",
        "tr": "Maldivler",
        "zh": "马尔代夫",
        "ja": "モルディブ"
    },
    "Mali": {
        "de": "Mali",
        "en": "Mali",
        "pl": "Mali",
        "es": "Malí",
        "fr": "Mali",
        "it": "Mali",
        "pt": "Mali",
        "ru": "Мали",
        "tr": "Mali",
        "zh": "马里",
        "ja": "マリ"
    },
    "Malta": {
        "de": "Malta",
        "en": "Malta",
        "pl": "Malta",
        "es": "Malta",
        "fr": "Malte",
        "it": "Malta",
        "pt": "Malta",
        "ru": "Мальта",
        "tr": "Malta",
        "zh": "马耳他",
        "ja": "マルタ"
    },
    "Marshall Islands": {
        "de": "Marshallinseln",
        "en": "Marshall Islands",
        "pl": "Wyspy Marshalla",
        "es": "Islas Marshall",
        "fr": "Îles Marshall",
        "it": "Isole Marshall",
        "pt": "Ilhas Marshall",
        "ru": "Маршалловы Острова",
        "tr": "Marshall Adaları",
        "zh": "马绍尔群岛",
        "ja": "マーシャル諸島"
    },
    "Martinique": {
        "de": "Martinique",
        "en": "Martinique",
        "pl": "Martynika",
        "es": "Martinica",
        "fr": "Martinique",
        "it": "Martinica",
        "pt": "Martinica",
        "ru": "Мартиника",
        "tr": "Martinik",
        "zh": "马提尼克",
        "ja": "マルティニーク"
    },
    "Mauritania": {
        "de": "Mauretanien",
        "en": "Mauritania",
        "pl": "Mauretania",
        "es": "Mauritania",
        "fr": "Mauritanie",
        "it": "Mauritania",
        "pt": "Mauritânia",
        "ru": "Мавритания",
        "tr": "Moritanya",
        "zh": "毛里塔尼亚",
        "ja": "モーリタニア"
    },
    "Mauritius": {
        "de": "Mauritius",
        "en": "Mauritius",
        "pl": "Mauritius",
        "es": "Mauricio",
        "fr": "Maurice",
        "it": "Mauritius",
        "pt": "Maurícia",
        "ru": "Маврикий",
        "tr": "Mauritius",
        "zh": "毛里求斯",
        "ja": "モーリシャス"
    },
    "Mayotte": {
        "de": "Mayotte",
        "en": "Mayotte",
        "pl": "Majotta",
        "es": "Mayotte",
        "fr": "Mayotte",
        "it": "Mayotte",
        "pt": "Mayotte",
        "ru": "Майотта",
        "tr": "Mayotte",
        "zh": "马约特",
        "ja": "マヨット"
    },
    "Mexico": {
        "de": "Mexiko",
        "en": "Mexico",
        "pl": "Meksyk",
        "es": "México",
        "fr": "Mexique",
        "it": "Messico",
        "pt": "México",
        "ru": "Мексика",
        "tr": "Meksika",
        "zh": "墨西哥",
        "ja": "メキシコ"
    },
    "Micronesia, Federated States of": {
        "de": "Mikronesien",
        "en": "Micronesia",
        "pl": "Mikronezja",
        "es": "Micronesia",
        "fr": "Micronésie",
        "it": "Micronesia",
        "pt": "Micronésia",
        "ru": "Микронезия",
        "tr": "Mikronezya",
        "zh": "密克罗尼西亚",
        "ja": "ミクロネシア"
    },
    "Moldova, Republic of": {
        "de": "Moldau",
        "en": "Moldova",
        "pl": "Mołdawia",
        "es": "Moldavia",
        "fr": "Moldavie",
        "it": "Moldavia",
        "pt": "Moldávia",
        "ru": "Молдова",
        "tr": "Moldova",
        "zh": "摩尔多瓦",
        "ja": "モルドバ"
    },
    "Monaco": {
        "de": "Monaco",
        "en": "Monaco",
        "pl": "Monako",
        "es": "Mónaco",
        "fr": "Monaco",
        "it": "Monaco",
        "pt": "Mónaco",
        "ru": "Монако",
        "tr": "Monako",
        "zh": "摩纳哥",
        "ja": "モナコ"
    },
    "Mongolia": {
        "de": "Mongolei",
        "en": "Mongolia",
        "pl": "Mongolia",
        "es": "Mongolia",
        "fr": "Mongolie",
        "it": "Mongolia",
        "pt": "Mongólia",
        "ru": "Монголия",
        "tr": "Moğolistan",
        "zh": "蒙古",
        "ja": "モンゴル"
    },
    "Montenegro": {
        "de": "Montenegro",
        "en": "Montenegro",
        "pl": "Czarnogóra",
        "es": "Montenegro",
        "fr": "Monténégro",
        "it": "Montenegro",
        "pt": "Montenegro",
        "ru": "Черногория",
        "tr": "Karadağ",
        "zh": "黑山",
        "ja": "モンテネグロ"
    },
    "Montserrat": {
        "de": "Montserrat",
        "en": "Montserrat",
        "pl": "Montserrat",
        "es": "Montserrat",
        "fr": "Montserrat",
        "it": "Montserrat",
        "pt": "Montserrat",
        "ru": "Монтсеррат",
        "tr": "Montserrat",
        "zh": "蒙特塞拉特",
        "ja": "モントセラト"
    },
    "Morocco": {
        "de": "Marokko",
        "en": "Morocco",
        "pl": "Maroko",
        "es": "Marruecos",
        "fr": "Maroc",
        "it": "Marocco",
        "pt": "Marrocos",
        "ru": "Марокко",
        "tr": "Fas",
        "zh": "摩洛哥",
        "ja": "モロッコ"
    },
    "Mozambique": {
        "de": "Mosambik",
        "en": "Mozambique",
        "pl": "Mozambik",
        "es": "Mozambique",
        "fr": "Mozambique",
        "it": "Mozambico",
        "pt": "Moçambique",
        "ru": "Мозамбик",
        "tr": "Mozambik",
        "zh": "莫桑比克",
        "ja": "モザンビーク"
    },
    "Myanmar": {
        "de": "Myanmar",
        "en": "Myanmar",
        "pl": "Mjanma",
        "es": "Myanmar",
        "fr": "Myanmar",
        "it": "Myanmar",
        "pt": "Mianmar",
        "ru": "Мьянма",
        "tr": "Myanmar",
        "zh": "缅甸",
        "ja": "ミャンマー"
    },
    "Namibia": {
        "de": "Namibia",
        "en": "Namibia",
        "pl": "Namibia",
        "es": "Namibia",
        "fr": "Namibie",
        "it": "Namibia",
        "pt": "Namíbia",
        "ru": "Намибия",
        "tr": "Namibya",
        "zh": "纳米比亚",
        "ja": "ナミビア"
    },
    "Nauru": {
        "de": "Nauru",
        "en": "Nauru",
        "pl": "Nauru",
        "es": "Nauru",
        "fr": "Nauru",
        "it": "Nauru",
        "pt": "Nauru",
        "ru": "Науру",
        "tr": "Nauru",
        "zh": "瑙鲁",
        "ja": "ナウル"
    },
    "Nepal": {
        "de": "Nepal",
        "en": "Nepal",
        "pl": "Nepal",
        "es": "Nepal",
        "fr": "Népal",
        "it": "Nepal",
        "pt": "Nepal",
        "ru": "Непал",
        "tr": "Nepal",
        "zh": "尼泊尔",
        "ja": "ネパール"
    },
    "Netherlands": {
        "de": "Niederlande",
        "en": "Netherlands",
        "pl": "Holandia",
        "es": "Países Bajos",
        "fr": "Pays-Bas",
        "it": "Paesi Bassi",
        "pt": "Países Baixos",
        "ru": "Нидерланды",
        "tr": "Hollanda",
        "zh": "荷兰",
        "ja": "オランダ"
    },
    "New Caledonia": {
        "de": "Neukaledonien",
        "en": "New Caledonia",
        "pl": "Nowa Kaledonia",
        "es": "Nueva Caledonia",
        "fr": "Nouvelle-Calédonie",
        "it": "Nuova Caledonia",
        "pt": "Nova Caledônia",
        "ru": "Новая Каледония",
        "tr": "Yeni Kaledonya",
        "zh": "新喀里多尼亚",
        "ja": "ニューカレドニア"
    },
    "New Zealand": {
        "de": "Neuseeland",
        "en": "New Zealand",
        "pl": "Nowa Zelandia",
        "es": "Nueva Zelanda",
        "fr": "Nouvelle-Zélande",
        "it": "Nuova Zelanda",
        "pt": "Nova Zelândia",
        "ru": "Новая Зеландия",
        "tr": "Yeni Zelanda",
        "zh": "新西兰",
        "ja": "ニュージーランド"
    },
    "Nicaragua": {
        "de": "Nicaragua",
        "en": "Nicaragua",
        "pl": "Nikaragua",
        "es": "Nicaragua",
        "fr": "Nicaragua",
        "it": "Nicaragua",
        "pt": "Nicarágua",
        "ru": "Никарагуа",
        "tr": "Nikaragua",
        "zh": "尼加拉瓜",
        "ja": "ニカラグア"
    },
    "Niger": {
        "de": "Niger",
        "en": "Niger",
        "pl": "Niger",
        "es": "Níger",
        "fr": "Niger",
        "it": "Niger",
        "pt": "Níger",
        "ru": "Нигер",
        "tr": "Nijer",
        "zh": "尼日尔",
        "ja": "ニジェール"
    },
    "Nigeria": {
        "de": "Nigeria",
        "en": "Nigeria",
        "pl": "Nigeria",
        "es": "Nigeria",
        "fr": "Nigéria",
        "it": "Nigeria",
        "pt": "Nigéria",
        "ru": "Нигерия",
        "tr": "Nijerya",
        "zh": "尼日利亚",
        "ja": "ナイジェリア"
    },
    "Niue": {
        "de": "Niue",
        "en": "Niue",
        "pl": "Niue",
        "es": "Niue",
        "fr": "Niue",
        "it": "Niue",
        "pt": "Niue",
        "ru": "Ниуэ",
        "tr": "Niue",
        "zh": "纽埃",
        "ja": "ニウエ"
    },
    "Norfolk Island": {
        "de": "Norfolkinsel",
        "en": "Norfolk Island",
        "pl": "Wyspa Norfolk",
        "es": "Isla Norfolk",
        "fr": "Île Norfolk",
        "it": "Isola Norfolk",
        "pt": "Ilha Norfolk",
        "ru": "Остров Норфолк",
        "tr": "Norfolk Adası",
        "zh": "诺福克岛",
        "ja": "ノーフォーク島"
    },
    "North Macedonia": {
        "de": "Nordmazedonien",
        "en": "North Macedonia",
        "pl": "Macedonia Północna",
        "es": "Macedonia del Norte",
        "fr": "Macédoine du Nord",
        "it": "Macedonia del Nord",
        "pt": "Macedônia do Norte",
        "ru": "Северная Македония",
        "tr": "Kuzey Makedonya",
        "zh": "北马其顿",
        "ja": "北マケドニア"
    },
    "Northern Ireland": {
        "de": "Nordirland",
        "en": "Northern Ireland",
        "pl": "Irlandia Północna",
        "es": "Irlanda del Norte",
        "fr": "Irlande du Nord",
        "it": "Irlanda del Nord",
        "pt": "Irlanda do Norte",
        "ru": "Северная Ирландия",
        "tr": "Kuzey İrlanda",
        "zh": "北爱尔兰",
        "ja": "北アイルランド"
    },
    "Northern Mariana Islands": {
        "de": "Nördliche Marianen",
        "en": "Northern Mariana Islands",
        "pl": "Mariany Północne",
        "es": "Islas Marianas del Norte",
        "fr": "Îles Mariannes du Nord",
        "it": "Isole Marianne Settentrionali",
        "pt": "Ilhas Marianas do Norte",
        "ru": "Северные Марианские острова",
        "tr": "Kuzey Mariana Adaları",
        "zh": "北马里亚纳群岛",
        "ja": "北マリアナ諸島"
    },
    "Norway": {
        "de": "Norwegen",
        "en": "Norway",
        "pl": "Norwegia",
        "es": "Noruega",
        "fr": "Norvège",
        "it": "Norvegia",
        "pt": "Noruega",
        "ru": "Норвегия",
        "tr": "Norveç",
        "zh": "挪威",
        "ja": "ノルウェー"
    },
    "Oman": {
        "de": "Oman",
        "en": "Oman",
        "pl": "Oman",
        "es": "Omán",
        "fr": "Oman",
        "it": "Oman",
        "pt": "Omã",
        "ru": "Оман",
        "tr": "Umman",
        "zh": "阿曼",
        "ja": "オマーン"
    },
    "Pakistan": {
        "de": "Pakistan",
        "en": "Pakistan",
        "pl": "Pakistan",
        "es": "Pakistán",
        "fr": "Pakistan",
        "it": "Pakistan",
        "pt": "Paquistão",
        "ru": "Пакистан",
        "tr": "Pakistan",
        "zh": "巴基斯坦",
        "ja": "パキスタン"
    },
    "Palau": {
        "de": "Palau",
        "en": "Palau",
        "pl": "Palau",
        "es": "Palaos",
        "fr": "Palaos",
        "it": "Palau",
        "pt": "Palau",
        "ru": "Палау",
        "tr": "Palau",
        "zh": "帕劳",
        "ja": "パラオ"
    },
    "Palestine": {
        "de": "Palästina",
        "en": "Palestine",
        "pl": "Palestyna",
        "es": "Palestina",
        "fr": "Palestine",
        "it": "Palestina",
        "pt": "Palestina",
        "ru": "Палестина",
        "tr": "Filistin",
        "zh": "巴勒斯坦",
        "ja": "パレスチナ"
    },
    "Panama": {
        "de": "Panama",
        "en": "Panama",
        "pl": "Panama",
        "es": "Panamá",
        "fr": "Panama",
        "it": "Panama",
        "pt": "Panamá",
        "ru": "Панама",
        "tr": "Panama",
        "zh": "巴拿马",
        "ja": "パナマ"
    },
    "Papua New Guinea": {
        "de": "Papua-Neuguinea",
        "en": "Papua New Guinea",
        "pl": "Papua-Nowa Gwinea",
        "es": "Papúa Nueva Guinea",
        "fr": "Papouasie-Nouvelle-Guinée",
        "it": "Papua Nuova Guinea",
        "pt": "Papua-Nova Guiné",
        "ru": "Папуа — Новая Гвинея",
        "tr": "Papua Yeni Gine",
        "zh": "巴布亚新几内亚",
        "ja": "パプアニューギニア"
    },
    "Paraguay": {
        "de": "Paraguay",
        "en": "Paraguay",
        "pl": "Paragwaj",
        "es": "Paraguay",
        "fr": "Paraguay",
        "it": "Paraguay",
        "pt": "Paraguai",
        "ru": "Парагвай",
        "tr": "Paraguay",
        "zh": "巴拉圭",
        "ja": "パラグアイ"
    },
    "Peru": {
        "de": "Peru",
        "en": "Peru",
        "pl": "Peru",
        "es": "Perú",
        "fr": "Pérou",
        "it": "Perù",
        "pt": "Peru",
        "ru": "Перу",
        "tr": "Peru",
        "zh": "秘鲁",
        "ja": "ペルー"
    },
    "Philippines": {
        "de": "Philippinen",
        "en": "Philippines",
        "pl": "Filipiny",
        "es": "Filipinas",
        "fr": "Philippines",
        "it": "Filippine",
        "pt": "Filipinas",
        "ru": "Филиппины",
        "tr": "Filipinler",
        "zh": "菲律宾",
        "ja": "フィリピン"
    },
    "Pitcairn": {
        "de": "Pitcairninseln",
        "en": "Pitcairn",
        "pl": "Pitcairn",
        "es": "Islas Pitcairn",
        "fr": "Îles Pitcairn",
        "it": "Isole Pitcairn",
        "pt": "Ilhas Pitcairn",
        "ru": "Питкэрн",
        "tr": "Pitcairn Adaları",
        "zh": "皮特凯恩群岛",
        "ja": "ピトケアン"
    },
    "Poland": {
        "de": "Polen",
        "en": "Poland",
        "pl": "Polska",
        "es": "Polonia",
        "fr": "Pologne",
        "it": "Polonia",
        "pt": "Polónia",
        "ru": "Польша",
        "tr": "Polonya",
        "zh": "波兰",
        "ja": "ポーランド"
    },
    "Portugal": {
        "de": "Portugal",
        "en": "Portugal",
        "pl": "Portugalia",
        "es": "Portugal",
        "fr": "Portugal",
        "it": "Portogallo",
        "pt": "Portugal",
        "ru": "Португалия",
        "tr": "Portekiz",
        "zh": "葡萄牙",
        "ja": "ポルトガル"
    },
    "Puerto Rico": {
        "de": "Puerto Rico",
        "en": "Puerto Rico",
        "pl": "Portoryko",
        "es": "Puerto Rico",
        "fr": "Porto Rico",
        "it": "Porto Rico",
        "pt": "Porto Rico",
        "ru": "Пуэрто-Рико",
        "tr": "Porto Riko",
        "zh": "波多黎各",
        "ja": "プエルトリコ"
    },
    "Qatar": {
        "de": "Katar",
        "en": "Qatar",
        "pl": "Katar",
        "es": "Catar",
        "fr": "Qatar",
        "it": "Qatar",
        "pt": "Catar",
        "ru": "Катар",
        "tr": "Katar",
        "zh": "卡塔尔",
        "ja": "カタール"
    },
    "Reunion": {
        "de": "Réunion",
        "en": "Reunion",
        "pl": "Reunion",
        "es": "Reunión",
        "fr": "La Réunion",
        "it": "Riunione",
        "pt": "Reunião",
        "ru": "Реюньон",
        "tr": "Réunion",
        "zh": "留尼汪",
        "ja": "レユニオン"
    },
    "Romania": {
        "de": "Rumänien",
        "en": "Romania",
        "pl": "Rumunia",
        "es": "Rumanía",
        "fr": "Roumanie",
        "it": "Romania",
        "pt": "Roménia",
        "ru": "Румыния",
        "tr": "Romanya",
        "zh": "罗马尼亚",
        "ja": "ルーマニア"
    },
    "Russian Federation": {
        "de": "Russland",
        "en": "Russia",
        "pl": "Rosja",
        "es": "Rusia",
        "fr": "Russie",
        "it": "Russia",
        "pt": "Rússia",
        "ru": "Россия",
        "tr": "Rusya",
        "zh": "俄罗斯",
        "ja": "ロシア"
    },
    "Rwanda": {
        "de": "Ruanda",
        "en": "Rwanda",
        "pl": "Rwanda",
        "es": "Ruanda",
        "fr": "Rwanda",
        "it": "Ruanda",
        "pt": "Ruanda",
        "ru": "Руанда",
        "tr": "Ruanda",
        "zh": "卢旺达",
        "ja": "ルワンダ"
    },
    "Saint Barthelemy": {
        "de": "Saint-Barthélemy",
        "en": "Saint Barthelemy",
        "pl": "Saint-Barthélemy",
        "es": "San Bartolomé",
        "fr": "Saint-Barthélemy",
        "it": "Saint-Barthélemy",
        "pt": "São Bartolomeu",
        "ru": "Сен-Бартелеми",
        "tr": "Saint Barthelemy",
        "zh": "圣巴泰勒米",
        "ja": "サン・バルテルミー"
    },
    "Saint Helena, Ascension and Tristan da Cunha": {
        "de": "St. Helena, Ascension und Tristan da Cunha",
        "en": "Saint Helena, Ascension and Tristan da Cunha",
        "pl": "Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha",
        "es": "Santa Elena, Ascensión y Tristán de Acuña",
        "fr": "Sainte-Hélène, Ascension et Tristan da Cunha",
        "it": "Sant'Elena, Ascensione e Tristan da Cunha",
        "pt": "Santa Helena, Ascensão e Tristão da Cunha",
        "ru": "Острова Святой Елены, Вознесения и Тристан-да-Кунья",
        "tr": "Saint Helena, Ascension ve Tristan da Cunha",
        "zh": "圣赫勒拿、阿森松和特里斯坦-达库尼亚",
        "ja": "セントヘレナ・アセンションおよびトリスタンダクーニャ"
    },
    "Saint Kitts and Nevis": {
        "de": "St. Kitts und Nevis",
        "en": "Saint Kitts and Nevis",
        "pl": "Saint Kitts i Nevis",
        "es": "San Cristóbal y Nieves",
        "fr": "Saint-Christophe-et-Niévès",
        "it": "Saint Kitts e Nevis",
        "pt": "São Cristóvão e Nevis",
        "ru": "Сент-Китс и Невис",
        "tr": "Saint Kitts ve Nevis",
        "zh": "圣基茨和尼维斯",
        "ja": "セントクリストファー・ネイビス"
    },
    "Saint Lucia": {
        "de": "St. Lucia",
        "en": "Saint Lucia",
        "pl": "Saint Lucia",
        "es": "Santa Lucía",
        "fr": "Sainte-Lucie",
        "it": "Santa Lucia",
        "pt": "Santa Lúcia",
        "ru": "Сент-Люсия",
        "tr": "Saint Lucia",
        "zh": "圣卢西亚",
        "ja": "セントルシア"
    },
    "Saint Martin": {
        "de": "Saint-Martin",
        "en": "Saint Martin",
        "pl": "Saint-Martin",
        "es": "San Martín",
        "fr": "Saint-Martin",
        "it": "Saint-Martin",
        "pt": "São Martinho",
        "ru": "Сен-Мартен",
        "tr": "Saint Martin",
        "zh": "圣马丁",
        "ja": "サン・マルタン"
    },
    "Saint Pierre and Miquelon": {
        "de": "Saint-Pierre und Miquelon",
        "en": "Saint Pierre and Miquelon",
        "pl": "Saint-Pierre i Miquelon",
        "es": "San Pedro y Miquelón",
        "fr": "Saint-Pierre-et-Miquelon",
        "it": "Saint-Pierre e Miquelon",
        "pt": "São Pedro e Miquelão",
        "ru": "Сен-Пьер и Микелон",
        "tr": "Saint Pierre ve Miquelon",
        "zh": "圣皮埃尔和密克隆",
        "ja": "サンピエール島・ミクロン島"
    },
    "Saint Vincent and the Grenadines": {
        "de": "St. Vincent und die Grenadinen",
        "en": "Saint Vincent and the Grenadines",
        "pl": "Saint Vincent i Grenadyny",
        "es": "San Vicente y las Granadinas",
        "fr": "Saint-Vincent-et-les-Grenadines",
        "it": "Saint Vincent e Grenadine",
        "pt": "São Vicente e Granadinas",
        "ru": "Сент-Винсент и Гренадины",
        "tr": "Saint Vincent ve Grenadinler",
        "zh": "圣文森特和格林纳丁斯",
        "ja": "セントビンセントおよびグレナディーン諸島"
    },
    "Samoa": {
        "de": "Samoa",
        "en": "Samoa",
        "pl": "Samoa",
        "es": "Samoa",
        "fr": "Samoa",
        "it": "Samoa",
        "pt": "Samoa",
        "ru": "Самоа",
        "tr": "Samoa",
        "zh": "萨摩亚",
        "ja": "サモア"
    },
    "San Marino": {
        "de": "San Marino",
        "en": "San Marino",
        "pl": "San Marino",
        "es": "San Marino",
        "fr": "Saint-Marin",
        "it": "San Marino",
        "pt": "São Marinho",
        "ru": "Сан-Марино",
        "tr": "San Marino",
        "zh": "圣马力诺",
        "ja": "サンマリノ"
    },
    "Sao Tome and Principe": {
        "de": "São Tomé und Príncipe",
        "en": "Sao Tome and Principe",
        "pl": "Wyspy Świętego Tomasza i Książęca",
        "es": "Santo Tomé y Príncipe",
        "fr": "Sao Tomé-et-Principe",
        "it": "São Tomé e Príncipe",
        "pt": "São Tomé e Príncipe",
        "ru": "Сан-Томе и Принсипи",
        "tr": "São Tomé ve Príncipe",
        "zh": "圣多美和普林西比",
        "ja": "サントメ・プリンシペ"
    },
    "Saudi Arabia": {
        "de": "Saudi-Arabien",
        "en": "Saudi Arabia",
        "pl": "Arabia Saudyjska",
        "es": "Arabia Saudita",
        "fr": "Arabie saoudite",
        "it": "Arabia Saudita",
        "pt": "Arábia Saudita",
        "ru": "Саудовская Аравия",
        "tr": "Suudi Arabistan",
        "zh": "沙特阿拉伯",
        "ja": "サウジアラビア"
    },
    "Scotland": {
        "de": "Schottland",
        "en": "Scotland",
        "pl": "Szkocja",
        "es": "Escocia",
        "fr": "Écosse",
        "it": "Scozia",
        "pt": "Escócia",
        "ru": "Шотландия",
        "tr": "İskoçya",
        "zh": "苏格兰",
        "ja": "スコットランド"
    },
    "Senegal": {
        "de": "Senegal",
        "en": "Senegal",
        "pl": "Senegal",
        "es": "Senegal",
        "fr": "Sénégal",
        "it": "Senegal",
        "pt": "Senegal",
        "ru": "Сенегал",
        "tr": "Senegal",
        "zh": "塞内加尔",
        "ja": "セネガル"
    },
    "Serbia": {
        "de": "Serbien",
        "en": "Serbia",
        "pl": "Serbia",
        "es": "Serbia",
        "fr": "Serbie",
        "it": "Serbia",
        "pt": "Sérvia",
        "ru": "Сербия",
        "tr": "Sırbistan",
        "zh": "塞尔维亚",
        "ja": "セルビア"
    },
    "Seychelles": {
        "de": "Seychellen",
        "en": "Seychelles",
        "pl": "Seszele",
        "es": "Seychelles",
        "fr": "Seychelles",
        "it": "Seychelles",
        "pt": "Seicheles",
        "ru": "Сейшельские Острова",
        "tr": "Seyşeller",
        "zh": "塞舌尔",
        "ja": "セーシェル"
    },
    "Sierra Leone": {
        "de": "Sierra Leone",
        "en": "Sierra Leone",
        "pl": "Sierra Leone",
        "es": "Sierra Leona",
        "fr": "Sierra Leone",
        "it": "Sierra Leone",
        "pt": "Serra Leoa",
        "ru": "Сьерра-Леоне",
        "tr": "Sierra Leone",
        "zh": "塞拉利昂",
        "ja": "シエラレオネ"
    },
    "Singapore": {
        "de": "Singapur",
        "en": "Singapore",
        "pl": "Singapur",
        "es": "Singapur",
        "fr": "Singapour",
        "it": "Singapore",
        "pt": "Singapura",
        "ru": "Сингапур",
        "tr": "Singapur",
        "zh": "新加坡",
        "ja": "シンガポール"
    },
    "Sint Maarten (Dutch part)": {
        "de": "Sint Maarten (niederländischer Teil)",
        "en": "Sint Maarten (Dutch part)",
        "pl": "Sint Maarten (część holenderska)",
        "es": "Sint Maarten (parte holandesa)",
        "fr": "Saint-Martin (partie néerlandaise)",
        "it": "Sint Maarten (parte olandese)",
        "pt": "São Martinho (parte holandesa)",
        "ru": "Синт-Мартен (нидерландская часть)",
        "tr": "Sint Maarten (Hollanda kısmı)",
        "zh": "荷属圣马丁",
        "ja": "シント・マールテン（オランダ領）"
    },
    "Slovakia": {
        "de": "Slowakei",
        "en": "Slovakia",
        "pl": "Słowacja",
        "es": "Eslovaquia",
        "fr": "Slovaquie",
        "it": "Slovacchia",
        "pt": "Eslováquia",
        "ru": "Словакия",
        "tr": "Slovakya",
        "zh": "斯洛伐克",
        "ja": "スロバキア"
    },
    "Slovenia": {
        "de": "Slowenien",
        "en": "Slovenia",
        "pl": "Słowenia",
        "es": "Eslovenia",
        "fr": "Slovénie",
        "it": "Slovenia",
        "pt": "Eslovénia",
        "ru": "Словения",
        "tr": "Slovenya",
        "zh": "斯洛文尼亚",
        "ja": "スロベニア"
    },
    "Solomon Islands": {
        "de": "Salomonen",
        "en": "Solomon Islands",
        "pl": "Wyspy Salomona",
        "es": "Islas Salomón",
        "fr": "Îles Salomon",
        "it": "Isole Salomone",
        "pt": "Ilhas Salomão",
        "ru": "Соломоновы Острова",
        "tr": "Solomon Adaları",
        "zh": "所罗门群岛",
        "ja": "ソロモン諸島"
    },
    "Somalia": {
        "de": "Somalia",
        "en": "Somalia",
        "pl": "Somalia",
        "es": "Somalia",
        "fr": "Somalie",
        "it": "Somalia",
        "pt": "Somália",
        "ru": "Сомали",
        "tr": "Somali",
        "zh": "索马里",
        "ja": "ソマリア"
    },
    "South Africa": {
        "de": "Südafrika",
        "en": "South Africa",
        "pl": "Rep. Połud. Afryki",
        "es": "Sudáfrica",
        "fr": "Afrique du Sud",
        "it": "Sudafrica",
        "pt": "África do Sul",
        "ru": "Южная Африка",
        "tr": "Güney Afrika",
        "zh": "南非",
        "ja": "南アフリカ"
    },
    "South Georgia and the South Sandwich Islands": {
        "de": "Südgeorgien und die Südlichen Sandwichinseln",
        "en": "South Georgia and the South Sandwich Islands",
        "pl": "Georgia Południowa i Sandwich Południowy",
        "es": "Georgia del Sur y las Islas Sandwich del Sur",
        "fr": "Géorgie du Sud-et-les îles Sandwich du Sud",
        "it": "Georgia del Sud e Isole Sandwich Australi",
        "pt": "Geórgia do Sul e Ilhas Sandwich do Sul",
        "ru": "Южная Георгия и Южные Сандвичевы острова",
        "tr": "Güney Georgia ve Güney Sandwich Adaları",
        "zh": "南乔治亚岛和南桑威奇群岛",
        "ja": "サウスジョージア・サウスサンドウィッチ諸島"
    },
    "South Sudan": {
        "de": "Südsudan",
        "en": "South Sudan",
        "pl": "Sudan Południowy",
        "es": "Sudán del Sur",
        "fr": "Soudan du Sud",
        "it": "Sud Sudan",
        "pt": "Sudão do Sul",
        "ru": "Южный Судан",
        "tr": "Güney Sudan",
        "zh": "南苏丹",
        "ja": "南スーダン"
    },
    "Spain": {
        "de": "Spanien",
        "en": "Spain",
        "pl": "Hiszpania",
        "es": "España",
        "fr": "Espagne",
        "it": "Spagna",
        "pt": "Espanha",
        "ru": "Испания",
        "tr": "İspanya",
        "zh": "西班牙",
        "ja": "スペイン"
    },
    "Sri Lanka": {
        "de": "Sri Lanka",
        "en": "Sri Lanka",
        "pl": "Sri Lanka",
        "es": "Sri Lanka",
        "fr": "Sri Lanka",
        "it": "Sri Lanka",
        "pt": "Sri Lanka",
        "ru": "Шри-Ланка",
        "tr": "Sri Lanka",
        "zh": "斯里兰卡",
        "ja": "スリランカ"
    },
    "Sudan": {
        "de": "Sudan",
        "en": "Sudan",
        "pl": "Sudan",
        "es": "Sudán",
        "fr": "Soudan",
        "it": "Sudan",
        "pt": "Sudão",
        "ru": "Судан",
        "tr": "Sudan",
        "zh": "苏丹",
        "ja": "スーダン"
    },
    "Suriname": {
        "de": "Suriname",
        "en": "Suriname",
        "pl": "Surinam",
        "es": "Surinam",
        "fr": "Suriname",
        "it": "Suriname",
        "pt": "Suriname",
        "ru": "Суринам",
        "tr": "Surinam",
        "zh": "苏里南",
        "ja": "スリナム"
    },
    "Svalbard and Jan Mayen Islands": {
        "de": "Svalbard und Jan Mayen",
        "en": "Svalbard and Jan Mayen Islands",
        "pl": "Svalbard i Jan Mayen",
        "es": "Svalbard y Jan Mayen",
        "fr": "Svalbard et Île Jan Mayen",
        "it": "Svalbard e Jan Mayen",
        "pt": "Ilhas Svalbard e Jan Mayen",
        "ru": "Шпицберген и Ян-Майен",
        "tr": "Svalbard ve Jan Mayen Adaları",
        "zh": "斯瓦尔巴群岛和扬马延岛",
        "ja": "スバールバル諸島およびヤンマイエン島"
    },
    "Swaziland": {
        "de": "Swasiland",
        "en": "Swaziland",
        "pl": "Suazi",
        "es": "Suazilandia",
        "fr": "Swaziland",
        "it": "Swaziland",
        "pt": "Suazilândia",
        "ru": "Свазиленд",
        "tr": "Svaziland",
        "zh": "斯威士兰",
        "ja": "スワジランド"
    },
    "Sweden": {
        "de": "Schweden",
        "en": "Sweden",
        "pl": "Szwecja",
        "es": "Suecia",
        "fr": "Suède",
        "it": "Svezia",
        "pt": "Suécia",
        "ru": "Швеция",
        "tr": "İsveç",
        "zh": "瑞典",
        "ja": "スウェーデン"
    },
    "Switzerland": {
        "de": "Schweiz",
        "en": "Switzerland",
        "pl": "Szwajcaria",
        "es": "Suiza",
        "fr": "Suisse",
        "it": "Svizzera",
        "pt": "Suíça",
        "ru": "Швейцария",
        "tr": "İsviçre",
        "zh": "瑞士",
        "ja": "スイス"
    },
    "Syrian Arab Republic": {
        "de": "Syrien",
        "en": "Syria",
        "pl": "Syria",
        "es": "Siria",
        "fr": "Syrie",
        "it": "Siria",
        "pt": "Síria",
        "ru": "Сирия",
        "tr": "Suriye",
        "zh": "叙利亚",
        "ja": "シリア"
    },
    "Taiwan (Republic of China)": {
        "de": "Taiwan",
        "en": "Taiwan",
        "pl": "Tajwan",
        "es": "Taiwán",
        "fr": "Taïwan",
        "it": "Taiwan",
        "pt": "Taiwan",
        "ru": "Тайвань",
        "tr": "Tayvan",
        "zh": "台湾",
        "ja": "台湾"
    },
    "Tajikistan": {
        "de": "Tadschikistan",
        "en": "Tajikistan",
        "pl": "Tadżykistan",
        "es": "Tayikistán",
        "fr": "Tadjikistan",
        "it": "Tagikistan",
        "pt": "Tajiquistão",
        "ru": "Таджикистан",
        "tr": "Tacikistan",
        "zh": "塔吉克斯坦",
        "ja": "タジキスタン"
    },
    "Tanzania, United Republic of": {
        "de": "Tansania",
        "en": "Tanzania",
        "pl": "Tanzania",
        "es": "Tanzania",
        "fr": "Tanzanie",
        "it": "Tanzania",
        "pt": "Tanzânia",
        "ru": "Танзания",
        "tr": "Tanzanya",
        "zh": "坦桑尼亚",
        "ja": "タンザニア"
    },
    "Thailand": {
        "de": "Thailand",
        "en": "Thailand",
        "pl": "Tajlandia",
        "es": "Tailandia",
        "fr": "Thaïlande",
        "it": "Thailandia",
        "pt": "Tailândia",
        "ru": "Таиланд",
        "tr": "Tayland",
        "zh": "泰国",
        "ja": "タイ"
    },
    "Timor-Leste": {
        "de": "Osttimor",
        "en": "Timor-Leste",
        "pl": "Timor Wschodni",
        "es": "Timor Oriental",
        "fr": "Timor oriental",
        "it": "Timor Est",
        "pt": "Timor-Leste",
        "ru": "Восточный Тимор",
        "tr": "Doğu Timor",
        "zh": "东帝汶",
        "ja": "東ティモール"
    },
    "Togo": {
        "de": "Togo",
        "en": "Togo",
        "pl": "Togo",
        "es": "Togo",
        "fr": "Togo",
        "it": "Togo",
        "pt": "Togo",
        "ru": "Того",
        "tr": "Togo",
        "zh": "多哥",
        "ja": "トーゴ"
    },
    "Tokelau": {
        "de": "Tokelau",
        "en": "Tokelau",
        "pl": "Tokelau",
        "es": "Tokelau",
        "fr": "Tokelau",
        "it": "Tokelau",
        "pt": "Toquelau",
        "ru": "Токелау",
        "tr": "Tokelau",
        "zh": "托克劳",
        "ja": "トケラウ"
    },
    "Tonga": {
        "de": "Tonga",
        "en": "Tonga",
        "pl": "Tonga",
        "es": "Tonga",
        "fr": "Tonga",
        "it": "Tonga",
        "pt": "Tonga",
        "ru": "Тонга",
        "tr": "Tonga",
        "zh": "汤加",
        "ja": "トンガ"
    },
    "Trinidad and Tobago": {
        "de": "Trinidad und Tobago",
        "en": "Trinidad and Tobago",
        "pl": "Trynidad i Tobago",
        "es": "Trinidad y Tobago",
        "fr": "Trinité-et-Tobago",
        "it": "Trinidad e Tobago",
        "pt": "Trindade e Tobago",
        "ru": "Тринидад и Тобаго",
        "tr": "Trinidad ve Tobago",
        "zh": "特立尼达和多巴哥",
        "ja": "トリニダード・トバゴ"
    },
    "Tunisia": {
        "de": "Tunesien",
        "en": "Tunisia",
        "pl": "Tunezja",
        "es": "Túnez",
        "fr": "Tunisie",
        "it": "Tunisia",
        "pt": "Tunísia",
        "ru": "Тунис",
        "tr": "Tunus",
        "zh": "突尼斯",
        "ja": "チュニジア"
    },
    "Turkey": {
        "de": "Türkei",
        "en": "Turkey",
        "pl": "Turcja",
        "es": "Turquía",
        "fr": "Turquie",
        "it": "Turchia",
        "pt": "Turquia",
        "ru": "Турция",
        "tr": "Türkiye",
        "zh": "土耳其",
        "ja": "トルコ"
    },
    "Turkmenistan": {
        "de": "Turkmenistan",
        "en": "Turkmenistan",
        "pl": "Turkmenistan",
        "es": "Turkmenistán",
        "fr": "Turkménistan",
        "it": "Turkmenistan",
        "pt": "Turquemenistão",
        "ru": "Туркмения",
        "tr": "Türkmenistan",
        "zh": "土库曼斯坦",
        "ja": "トルクメニスタン"
    },
    "Turks and Caicos Islands": {
        "de": "Turks- und Caicosinseln",
        "en": "Turks and Caicos Islands",
        "pl": "Turks i Caicos",
        "es": "Islas Turcas y Caicos",
        "fr": "Îles Turques-et-Caïques",
        "it": "Isole Turks e Caicos",
        "pt": "Ilhas Turcas e Caicos",
        "ru": "Теркс и Кайкос",
        "tr": "Turks ve Caicos Adaları",
        "zh": "特克斯和凯科斯群岛",
        "ja": "タークス・カイコス諸島"
    },
    "Tuvalu": {
        "de": "Tuvalu",
        "en": "Tuvalu",
        "pl": "Tuvalu",
        "es": "Tuvalu",
        "fr": "Tuvalu",
        "it": "Tuvalu",
        "pt": "Tuvalu",
        "ru": "Тувалу",
        "tr": "Tuvalu",
        "zh": "图瓦卢",
        "ja": "ツバル"
    },
    "Uganda": {
        "de": "Uganda",
        "en": "Uganda",
        "pl": "Uganda",
        "es": "Uganda",
        "fr": "Ouganda",
        "it": "Uganda",
        "pt": "Uganda",
        "ru": "Уганда",
        "tr": "Uganda",
        "zh": "乌干达",
        "ja": "ウガンダ"
    },
    "Ukraine": {
        "de": "Ukraine",
        "en": "Ukraine",
        "pl": "Ukraina",
        "es": "Ucrania",
        "fr": "Ukraine",
        "it": "Ucraina",
        "pt": "Ucrânia",
        "ru": "Украина",
        "tr": "Ukrayna",
        "zh": "乌克兰",
        "ja": "ウクライナ"
    },
    "United Arab Emirates": {
        "de": "Vereinigte Arabische Emirate",
        "en": "United Arab Emirates",
        "pl": "Zjednoczone Emiraty Arabskie",
        "es": "Emiratos Árabes Unidos",
        "fr": "Émirats arabes unis",
        "it": "Emirati Arabi Uniti",
        "pt": "Emirados Árabes Unidos",
        "ru": "Объединённые Арабские Эмираты",
        "tr": "Birleşik Arap Emirlikleri",
        "zh": "阿拉伯联合酋长国",
        "ja": "アラブ首長国連邦"
    },
    "United Kingdom": {
        "de": "Vereinigtes Königreich",
        "en": "United Kingdom",
        "pl": "Wielka Brytania",
        "es": "Reino Unido",
        "fr": "Royaume-Uni",
        "it": "Regno Unito",
        "pt": "Reino Unido",
        "ru": "Великобритания",
        "tr": "Birleşik Krallık",
        "zh": "英国",
        "ja": "イギリス"
    },
    "United States": {
        "de": "USA",
        "en": "USA",
        "pl": "USA",
        "es": "EE. UU.",
        "fr": "États-Unis",
        "it": "USA",
        "pt": "EUA",
        "ru": "США",
        "tr": "ABD",
        "zh": "美国",
        "ja": "アメリカ合衆国"
    },
    "Uruguay": {
        "de": "Uruguay",
        "en": "Uruguay",
        "pl": "Urugwaj",
        "es": "Uruguay",
        "fr": "Uruguay",
        "it": "Uruguay",
        "pt": "Uruguai",
        "ru": "Уругвай",
        "tr": "Uruguay",
        "zh": "乌拉圭",
        "ja": "ウルグアイ"
    },
    "US Minor Outlying Islands": {
        "de": "Amerikanische Überseeinseln",
        "en": "US Minor Outlying Islands",
        "pl": "Dalekie Wyspy Mniejsze Stanów Zjednoczonych",
        "es": "Islas menores alejadas de EE. UU.",
        "fr": "Îles mineures éloignées des États-Unis",
        "it": "Isole minori esterne degli Stati Uniti",
        "pt": "Ilhas Menores Distantes dos EUA",
        "ru": "Внешние малые острова США",
        "tr": "ABD Küçük Dış Adaları",
        "zh": "美国本土外小岛屿",
        "ja": "アメリカ合衆国領有小離島"
    },
    "Uzbekistan": {
        "de": "Usbekistan",
        "en": "Uzbekistan",
        "pl": "Uzbekistan",
        "es": "Uzbekistán",
        "fr": "Ouzbékistan",
        "it": "Uzbekistan",
        "pt": "Uzbequistão",
        "ru": "Узбекистан",
        "tr": "Özbekistan",
        "zh": "乌兹别克斯坦",
        "ja": "ウズベキスタン"
    },
    "Vanuatu": {
        "de": "Vanuatu",
        "en": "Vanuatu",
        "pl": "Vanuatu",
        "es": "Vanuatu",
        "fr": "Vanuatu",
        "it": "Vanuatu",
        "pt": "Vanuatu",
        "ru": "Вануату",
        "tr": "Vanuatu",
        "zh": "瓦努阿图",
        "ja": "バヌアツ"
    },
    "Venezuela, Bolivarian Republic of": {
        "de": "Venezuela",
        "en": "Venezuela",
        "pl": "Wenezuela",
        "es": "Venezuela",
        "fr": "Venezuela",
        "it": "Venezuela",
        "pt": "Venezuela",
        "ru": "Венесуэла",
        "tr": "Venezuela",
        "zh": "委内瑞拉",
        "ja": "ベネズエラ"
    },
    "Vietnam": {
        "de": "Vietnam",
        "en": "Vietnam",
        "pl": "Wietnam",
        "es": "Vietnam",
        "fr": "Viêt Nam",
        "it": "Vietnam",
        "pt": "Vietname",
        "ru": "Вьетнам",
        "tr": "Vietnam",
        "zh": "越南",
        "ja": "ベトナム"
    },
    "Virgin Islands, British": {
        "de": "Britische Jungferninseln",
        "en": "British Virgin Islands",
        "pl": "Brytyjskie Wyspy Dziewicze",
        "es": "Islas Vírgenes Británicas",
        "fr": "Îles Vierges britanniques",
        "it": "Isole Vergini Britanniche",
        "pt": "Ilhas Virgens Britânicas",
        "ru": "Британские Виргинские острова",
        "tr": "Britanya Virjin Adaları",
        "zh": "英属维尔京群岛",
        "ja": "イギリス領ヴァージン諸島"
    },
    "Virgin Islands, U.S.": {
        "de": "Amerikanische Jungferninseln",
        "en": "U.S. Virgin Islands",
        "pl": "Wyspy Dziewicze Stanów Zjednoczonych",
        "es": "Islas Vírgenes de los Estados Unidos",
        "fr": "Îles Vierges des États-Unis",
        "it": "Isole Vergini Americane",
        "pt": "Ilhas Virgens Americanas",
        "ru": "Виргинские острова (США)",
        "tr": "ABD Virjin Adaları",
        "zh": "美属维尔京群岛",
        "ja": "アメリカ領ヴァージン諸島"
    },
    "Wales": {
        "de": "Wales",
        "en": "Wales",
        "pl": "Walia",
        "es": "Gales",
        "fr": "Pays de Galles",
        "it": "Galles",
        "pt": "País de Gales",
        "ru": "Уэльс",
        "tr": "Galler",
        "zh": "威尔士",
        "ja": "ウェールズ"
    },
    "Wallis and Futuna Islands": {
        "de": "Wallis und Futuna",
        "en": "Wallis and Futuna Islands",
        "pl": "Wallis i Futuna",
        "es": "Wallis y Futuna",
        "fr": "Wallis-et-Futuna",
        "it": "Wallis e Futuna",
        "pt": "Wallis e Futuna",
        "ru": "Уоллис и Футуна",
        "tr": "Wallis ve Futuna Adaları",
        "zh": "瓦利斯和富图纳群岛",
        "ja": "ウォリス・フツナ"
    },
    "Western Sahara": {
        "de": "Westsahara",
        "en": "Western Sahara",
        "pl": "Sahara Zachodnia",
        "es": "Sahara Occidental",
        "fr": "Sahara occidental",
        "it": "Sahara Occidentale",
        "pt": "Saara Ocidental",
        "ru": "Западная Сахара",
        "tr": "Batı Sahra",
        "zh": "西撒哈拉",
        "ja": "西サハラ"
    },
    "Yemen": {
        "de": "Jemen",
        "en": "Yemen",
        "pl": "Jemen",
        "es": "Yemen",
        "fr": "Yémen",
        "it": "Yemen",
        "pt": "Iémen",
        "ru": "Йемен",
        "tr": "Yemen",
        "zh": "也门",
        "ja": "イエメン"
    },
    "Zambia": {
        "de": "Sambia",
        "en": "Zambia",
        "pl": "Zambia",
        "es": "Zambia",
        "fr": "Zambie",
        "it": "Zambia",
        "pt": "Zâmbia",
        "ru": "Замбия",
        "tr": "Zambiya",
        "zh": "赞比亚",
        "ja": "ザンビア"
    },
    "Zimbabwe": {
        "de": "Simbabwe",
        "en": "Zimbabwe",
        "pl": "Zimbabwe",
        "es": "Zimbabue",
        "fr": "Zimbabwe",
        "it": "Zimbabwe",
        "pt": "Zimbábue",
        "ru": "Зимбабве",
        "tr": "Zimbabve",
        "zh": "津巴布韦",
        "ja": "ジンバブエ"
    }

};
